services:

  main:
    container_name: weighingTest1-laravel
    build: .
    restart: unless-stopped
    ports:
      - 9000:80

  db:
    image: "mysql:latest"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'torabika'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'adminiot'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'adminiot'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '33069:3306'
    expose:
      - '33069'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: